---
shib_idp_version: 3
shib_id_attribute: 'eduPersonPrincipalName'
shib_auth_attribute: 'eduPersonEntitlement'
shib_auth_values: set([
    'urn:mace:ubc.ca:grp:vancouver:employee:active',
    'urn:mace:ubc.ca:grp:student:current'])
shib_session_init_entityid: https://authentication.ubc.ca
shib_idp_metadata_uri: https://authentication.ubc.ca/idp/shibboleth
shibboleth_sso_entity_id: 'https://authentication.ubc.ca'
shibboleth_sso_discovery_url: 'https://authentication.ubc.ca/idp/shibboleth'
